version: '3.3'
services:
  db2:
    image: mysql:latest
    restart: always
    ports: 
        - "3306:3306"
    volumes:
        - .\dataMysql:/var/lib/mysql
        - .\initdb.d:/docker-entrypoint-initdb.d
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wordpress
        MYSQL_USER: chan
        MYSQL_PASSWORD: 961421180 