version: '3.3'
services:
  db2:
    image: mysql:latest
    restart: always
    ports: 
        - "3306:3306"
    volumes:
        - C:\DEVLAB\CURSOS_UDEMY\MYSQL_DB\CURSO_WEB2\data:/var/lib/mysql
        - C:\DEVLAB\CURSOS_UDEMY\MYSQL_DB\CURSO_WEB2\initdb.d:/docker-entrypoint-initdb.d
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wordpress
        MYSQL_USER: chan
        MYSQL_PASSWORD: 961421180 